### PR TITLE
[Swift 3] Migration

### PR DESCRIPTION
**Pull request by devladinci**
## Scope

- [x] Update pods
- [x] Migrate to Swift3
- [x] Fix `Sparkle` code signing

### CODE REVIEW

**Comment by andreasklinger** [comment]
bump :)

**Comment by acche** [comment]
Will release Swift 3?

**Comment by devladinci** [comment]
@ACChe Yes. Migration is done, but there are some issues with `Sparkle`.

**Comment by devladinci** [comment]
Merged.

**Pull request merged**
